# Change these first
owner: UnSeulT # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: InterAFOCG
    url: https://interafocg.org/
  - name: AMAP IdF
    url: https://amap-idf.org/
  - name: AMAPartage
    url: https://amapartage.fr/
  - name: Bio 34
    url: https://bio34.com/
  - name: Solidarité Paysans
    url: https://solidaritepaysans.org/
  - name: Emmaüs Le Maquis
    url: https://emmauslemaquis.org/
  - name: Solagro
    url: https://solagro.org
  - name: Afterres
    url: https://afterres.org
  - name: Metha BFC
    url: https://methabfc.fr/
  - name: Junior Association RNJA
    url: https://juniorassociation.org/
  - name: "Choeur à l'ouvrage"
    url: https://choeuralouvrage.org/
  - name: La place de la danse
    url: https://laplacedeladanse.com
  - name: LMAC
    url: https://reseau-lmac.fr
  - name: Dom Robert
    url: https://www.domrobert.com/
  - name: Encalcat Abbaye
    url: https://encalcat.com
  - name: Encalcat Boutique
    url: https://boutique.encalcat.com
  - name: Bénédictines Dourgne
    url: https://benedictines-dourgne.org/
  - name: Cocagne Acepp 31
    url: https://cocagne31.org
  - name: Moodle - Cocagne Acepp 31
    url: https://moodle.cocagne31.org
  - name: Accueil pour tous
    url: https://accueilpourtous31.fr
  - name: Bujinkan Toulouse
    url: https://bujinkan-toulouse.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  logoUrl: https://raw.githubusercontent.com/UnSeulT/upptime/master/assets/1t-rond.png
  name: Upptime A71T
  introTitle: "**Upptime**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). 
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
