# Change these first
owner: UnSeulT # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Solagro
    url: https://solagro.org
  - name: Osae
    url: https://osez-agroecologie.org
  - name: Afterres 2050
    url: http://afterres2050.solagro.org
  - name: Encalcat Abbaye
    url: https://encalcat.com
  - name: Encalcat Boutique
    url: https://boutique.encalcat.com
  - name: Dom Robert
    url: https://www.domrobert.com/
  - name: Graines del Païs
    url: https://grainesdelpais.com/
  - name: LMAC
    url: https://reseau-lmac.fr
  - name: La place de la danse
    url: https://laplacedeladanse.com
  - name: Fondation Écureuil
    url: https://caisseepargne-art-contemporain.fr/
  - name: Biaugerme
    url: https://www.biaugerme.com/
  - name: Junior Association RNJA
    url: https://juniorassociation.org/
  - name: Bio 34
    url: https://bio34.com/
  - name: Cocagne Acepp 31
    url: https://cocagne31.org
  - name: Moodle - Cocagne Acepp 31
    url: https://moodle.cocagne31.org
  - name: Accueil pour tous
    url: https://accueilpourtous31.fr
  - name: Tau
    url: https://tau.so
  - name: Bujinkan Toulouse
    url: https://bujinkan-toulouse.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  logoUrl: https://raw.githubusercontent.com/UnSeulT/upptime/master/assets/1t-rond.png
  name: Upptime A71T
  introTitle: "**Upptime**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). 
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
